print("Hello")
print("It was a dark and stormy night.")
print("Suddenly a shot rang out!")
print("Hi! This is a double quote mark: \" We use it for printing.")
print("Forrest Gump once said \"I just stopped running. I didn't feel like running anymore!.\"")